# Generated by Django 6.0.1 on 2026-01-19 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='emergencylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Emergency SOS Log', 'verbose_name_plural': 'Emergency SOS Logs'},
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='priority',
            field=models.IntegerField(default=1, help_text='1=Primary, 2=Secondary, etc.'),
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='activated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='emergency_services_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='medical_snapshot',
            field=models.JSONField(blank=True, help_text='Medical info at time of SOS', null=True),
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='dnr_order',
            field=models.BooleanField(default=False, help_text='Do Not Resuscitate order'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='insurance_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='previous_surgeries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='primary_doctor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='secondary_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='secondary_contact_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emergency_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
