recipe: default.v1
language: en
assistant_id: checkmycure_eye_health
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 17
  - name: DIETClassifier
    epochs: 50
policies:
  - name: RulePolicy
