# Generated by Django 6.0.1 on 2026-01-19 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='eye_scans/original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='eye_scans/processed/')),
                ('disease', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('detections', models.JSONField(default=dict, help_text='Full YOLO detection results')),
                ('recommendations', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
