# Generated by Django 6.0.1 on 2026-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_eyedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyedetection',
            name='causes',
            field=models.JSONField(default=list, help_text='List of causes'),
        ),
        migrations.AddField(
            model_name='eyedetection',
            name='disease_info',
            field=models.TextField(blank=True, help_text='Detailed disease information'),
        ),
        migrations.AddField(
            model_name='eyedetection',
            name='prevention',
            field=models.JSONField(default=list, help_text='Prevention measures'),
        ),
        migrations.AddField(
            model_name='eyedetection',
            name='symptoms',
            field=models.JSONField(default=list, help_text='List of symptoms'),
        ),
        migrations.AddField(
            model_name='eyedetection',
            name='treatment',
            field=models.TextField(blank=True, help_text='Treatment information'),
        ),
    ]
